GET http://localhost:3000/products  HTTP/1.1

###
GET http://localhost:3000/products/5f909c0850b2443af1ed5dc1  HTTP/1.1

######

POST http://localhost:3000/products HTTP/1.1
content-type: application/json


{ "name" : "popopopopo", "quantity" : 10 }

######

PUT http://localhost:3000/products/5f91f1b9c0f1fc54ac5c986b HTTP/1.1
content-type: application/json


{ "name" : "zzzzz", "quantity" : 222 }

###

DELETE http://localhost:3000/products/5f9097753ddbeb31d141f96b HTTP/1.1
content-type: application/json
